/*
 * DIO_INTERFACE.h
 *
 *  Created on: Sep 10, 2021
 *      Author: Ahmed Moataz
 */
//fanction prototype

#ifndef DIO_INTERFACE_H_
#define DIO_INTERFACE_H_

#define DIO_MAX_PORT_NB 4
#define DIO_MAX_PIN_NB 8

#define DIO_HIGH 1
#define DIO_LOW 0
#define GROUP_A 0 //PORTS
#define GROUP_B 1 //PORTS
#define GROUP_C 2 //PORTS
#define GROUP_D 3 //PORTS
#define DIO_INPUT 0 //IN DIRECTION (DDR)
#define DIO_OUTPUT 1 //IN DIRECTION (DDR)
#define DIO_MAX_PORT_VALUE 255
#define DIO_MAX_PORT_DIRECTION 255
#define DIO_PIN_0 0
#define DIO_PIN_1 1
#define DIO_PIN_2 2
#define DIO_PIN_3 3
#define DIO_PIN_4 4
#define DIO_PIN_5 5
#define DIO_PIN_6 6
#define DIO_PIN_7 7
u8 DIO_SET_PIN_VALUE(u8 PORT_NB,u8 PIN_NB,u8 PIN_VALUE);//RIGESTER PORT PIN PIN....
u8 DIO_SET_PIN_DIRECTION(u8 PORT_NB,u8 PIN_NB,u8 PIN_DIRECTION);//RIGESTER DDR PIN PIN....

u8 DIO_SET_PORT_VALUE(u8 PORT_NB,u8 PORT_VALUE);//RIGESTER PORT (PORT PORT....
u8 DIO_SET_PORT_DIRECTION(u8 PORT_NB,u8 PORT_DIRECTION);//RIGESTER DDR (PORT PORT....

u8 DIO_GET_PIN_VALUE(u8 PORT_NB,u8 PIN_NB,u8 *PIN_VALUE);//TO GET VALUE ON PIN 0 OR 1
u8 DIO_GET_PORT_VALUE(u8 PORT_NB,u8 *PORT_VALUE);//TO GET VALUE ON PORT 0 OR 1




#endif /* DIO_INTERFACE_H_ */
